apiVersion: v1
kind: Service
metadata:
  name: auto-discovery-auth-service
  namespace: auto-discovery
  labels:
    app: auto-discovery-auth-service
    tier: backend
    service: auth
spec:
  type: ClusterIP
  selector:
    app: auto-discovery-auth-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
