apiVersion: v1
kind: Service
metadata:
  name: auto-discovery-backend
  namespace: auto-discovery
  labels:
    app: auto-discovery-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: auto-discovery-backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
