apiVersion: v1
kind: Service
metadata:
  name: auto-discovery-vins-api
  namespace: auto-discovery
  labels:
    app: auto-discovery-vins-api
    tier: backend
    service: vins
spec:
  type: ClusterIP
  selector:
    app: auto-discovery-vins-api
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
